platform :ios, '8.0'

target 'MyPayPal' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyPayPal
  pod 'PayPal-iOS-SDK'

end
